<div id="climate_widget" class="widget">
  <div class="widget_title">
    On this day
  </div>
  <div class="widget_content" style="display:block;">
    <table class="table-all" style="width:100%;">
      <tbody>
        <tr>
          <td class="label">All-Time High</td>
          <td class="data"><b>$climate.day.outTemp.high.max</b></td>
          <td class="timestamp">$climate.day.outTemp.high.maxtime</td>
        </tr>
        <tr>
          <td class="label">Lowest High</td>
          <td class="data"><b>$climate.day.outTemp.high.min</b></td>
          <td class="timestamp">$climate.day.outTemp.high.mintime</td>
        </tr>
        <tr>
          <td class="label">Average High</td>
          <td class="data"><b>$climate.day.outTemp.high.avg</b></td>
          <td class="timestamp">&nbsp;</td>
        </tr>
        <tr>
          <td class="label">All-Time Low</td>
          <td class="data"><b>$climate.day.outTemp.low.min</b></td>
          <td class="timestamp">$climate.day.outTemp.low.mintime</td>
        </tr>
        <tr>
          <td class="label">Highest Low</td>
          <td class="data"><b>$climate.day.outTemp.low.max</b></td>
          <td class="timestamp">$climate.day.outTemp.low.maxtime</td>
        </tr>
        <tr>
          <td class="label">Average Low</td>
          <td class="data"><b>$climate.day.outTemp.low.avg</b></td>
          <td class="timestamp">&nbsp;</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>